### ISSUE TITLE
Sevice DownloadService has leaked ServiceConnection

### ISSUE THREAD

**Issue by mattleibow** [mattleibow/Android.Play.ExpansionLibrary#1]
Remove this exception: 

```
06-26 10:44:09.730 E/ActivityThread(29293): Service crosspuppy.PuppyDownloaderService has leaked ServiceConnection licenseverificationlibrary.LicenseChecker@4080b978 that was originally bound here
06-26 10:44:09.730 E/ActivityThread(29293): android.app.ServiceConnectionLeaked: Service crosspuppy.PuppyDownloaderService has leaked ServiceConnection licenseverificationlibrary.LicenseChecker@4080b978 that was originally bound here
06-26 10:44:09.730 E/ActivityThread(29293):     at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:923)
06-26 10:44:09.730 E/ActivityThread(29293):     at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:818)
06-26 10:44:09.730 E/ActivityThread(29293):     at android.app.ContextImpl.bindService(ContextImpl.java:1077)
06-26 10:44:09.730 E/ActivityThread(29293):     at android.content.ContextWrapper.bindService(ContextWrapper.java:370)
06-26 10:44:09.730 E/ActivityThread(29293):     at expansiondownloader.service.DownloaderService_LvlRunnable.n_run(Native Method)
06-26 10:44:09.730 E/ActivityThread(29293):     at expansiondownloader.service.DownloaderService_LvlRunnable.run(DownloaderService_LvlRunnable.java:36)
06-26 10:44:09.730 E/ActivityThread(29293):     at android.os.Handler.handleCallback(Handler.java:587)
06-26 10:44:09.730 E/ActivityThread(29293):     at android.os.Handler.dispatchMessage(Handler.java:92)
06-26 10:44:09.730 E/ActivityThread(29293):     at android.os.Looper.loop(Looper.java:132)
06-26 10:44:09.730 E/ActivityThread(29293):     at android.app.ActivityThread.main(ActivityThread.java:4025)
06-26 10:44:09.730 E/ActivityThread(29293):     at java.lang.reflect.Method.invokeNative(Native Method)
06-26 10:44:09.730 E/ActivityThread(29293):     at java.lang.reflect.Method.invoke(Method.java:491)
06-26 10:44:09.730 E/ActivityThread(29293):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
06-26 10:44:09.730 E/ActivityThread(29293):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
06-26 10:44:09.730 E/ActivityThread(29293):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by KonajuGames** [comment]
Is there a fix for this?  Having the app terminate after a download is not a good user experience.
